# Generated by Django 2.2.3 on 2019-07-07 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number2', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(7000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('clg_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=40)),
                ('slot', models.CharField(max_length=15)),
            ],
        ),
    ]
