# Generated by Django 2.2.3 on 2019-07-10 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number2',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(7000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
