# Generated by Django 2.2.3 on 2019-10-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lti_23_oct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=50)),
                ('number2', models.CharField(max_length=100)),
                ('clg_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=40)),
                ('qualification', models.CharField(max_length=100)),
                ('passingyear10', models.CharField(max_length=40)),
                ('percent10', models.CharField(max_length=40)),
                ('passingyear12', models.CharField(blank=True, max_length=40)),
                ('percent12', models.CharField(blank=True, max_length=40)),
                ('diplomapassyear', models.CharField(blank=True, max_length=40)),
                ('diplomapercent', models.CharField(blank=True, max_length=40)),
                ('pointer', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('confirmation', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
