# Generated by Django 2.2.3 on 2019-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0002_lti_23_oct'),
    ]

    operations = [
        migrations.AddField(
            model_name='lti_23_oct',
            name='tpoemail',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='lti_23_oct',
            name='tponame',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='lti_23_oct',
            name='tponumber',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
