# Generated by Django 2.2.3 on 2019-07-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0002_auto_20190710_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
