# Generated by Django 2.2.3 on 2019-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0003_auto_20191002_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='lti_23_oct',
            name='degreepassyear',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
