# Generated by Django 2.2.3 on 2019-07-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0003_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='confirmation',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='number2',
            field=models.BigIntegerField(),
        ),
    ]
