# Generated by Django 2.2.3 on 2019-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0004_lti_23_oct_degreepassyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='IBM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
                ('number2', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=40)),
                ('clg_name', models.CharField(max_length=100)),
                ('confirmation', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
