# Generated by Django 2.2.3 on 2019-07-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0004_auto_20190710_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True),
        ),
    ]
