# Generated by Django 2.2.3 on 2019-10-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0005_ibm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibm',
            name='confirmation',
        ),
    ]
