# Generated by Django 2.2.3 on 2019-07-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0006_auto_20190711_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
