# Generated by Django 2.2.3 on 2019-07-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0007_auto_20190711_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
