# Generated by Django 2.2.3 on 2019-10-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0008_ibm7oct'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbmResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('clg_name', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=40)),
            ],
        ),
    ]
