# Generated by Django 2.2.3 on 2019-07-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0008_remove_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number2',
            field=models.BigIntegerField(unique=True),
        ),
    ]
