# Generated by Django 2.2.3 on 2019-10-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0009_ibmresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='infosys15oct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('number2', models.CharField(max_length=100)),
                ('clg_name', models.CharField(max_length=100)),
                ('slot', models.CharField(blank=True, max_length=50)),
                ('confirmation', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
