# Generated by Django 2.2.3 on 2019-07-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0009_auto_20190712_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slot',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
