# Generated by Django 2.2.3 on 2019-07-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0010_auto_20190712_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='number2',
            field=models.BigIntegerField(),
        ),
    ]
