# Generated by Django 2.2.3 on 2019-10-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0011_infosys16oct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infosys15Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('clg_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Infosys16Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('clg_name', models.CharField(max_length=120)),
            ],
        ),
    ]
