# Generated by Django 2.2.5 on 2019-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0012_auto_20190917_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_1_Salasar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number2', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('clg_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=40)),
                ('slot', models.CharField(blank=True, max_length=15)),
                ('confirmation', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
