# Generated by Django 2.2.3 on 2019-10-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0012_infosys15result_infosys16result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infosys15result',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='infosys16result',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='infosys15result',
            name='lastname',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='infosys16result',
            name='lastname',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
