# Generated by Django 2.2.3 on 2019-10-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0014_finalinfosys'),
    ]

    operations = [
        migrations.CreateModel(
            name='finallistinfosys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('middlename', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('clg_name', models.CharField(max_length=120)),
                ('branch', models.CharField(max_length=40)),
            ],
        ),
    ]
