# Generated by Django 2.2.3 on 2019-11-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0018_lti20nov'),
    ]

    operations = [
        migrations.CreateModel(
            name='lti12result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clg_name', models.CharField(max_length=100)),
            ],
        ),
    ]
