# Generated by Django 2.2.3 on 2019-12-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0024_swab12dec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swab12dec',
            name='clg_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
