# Generated by Django 2.2.3 on 2019-12-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0025_auto_20191211_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swab12dec',
            name='slot',
        ),
        migrations.AddField(
            model_name='swab12dec',
            name='branch',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
