# Generated by Django 2.2.3 on 2020-01-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0027_cap8jan'),
    ]

    operations = [
        migrations.CreateModel(
            name='zycus11jan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('number2', models.CharField(max_length=100)),
                ('clg_name', models.CharField(blank=True, max_length=100)),
                ('degtype', models.CharField(max_length=15)),
                ('branch', models.CharField(blank=True, max_length=40)),
                ('confirmation', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
