# Generated by Django 2.2.3 on 2020-01-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0028_zycus11jan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zycus11jan',
            name='email',
        ),
    ]
