# Generated by Django 2.2.3 on 2020-01-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0029_remove_zycus11jan_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='zycus11jan',
        ),
    ]
