# Generated by Django 2.2.3 on 2020-03-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0031_zycus11jan'),
    ]

    operations = [
        migrations.AddField(
            model_name='swab12dec',
            name='passyear',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
