# Generated by Django 2.2.3 on 2020-03-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0032_swab12dec_passyear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='swab12dec',
        ),
    ]
