# Generated by Django 2.2.3 on 2020-03-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0033_delete_swab12dec'),
    ]

    operations = [
        migrations.CreateModel(
            name='swab12dec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('number2', models.CharField(max_length=100)),
                ('clg_name', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, max_length=40)),
                ('passyear', models.CharField(blank=True, max_length=20)),
                ('confirmation', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
