# Generated by Django 2.2.3 on 2020-03-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0035_virt11mar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='virt11mar',
        ),
    ]
