# Generated by Django 2.2.3 on 2020-05-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0037_virt11mar'),
    ]

    operations = [
        migrations.CreateModel(
            name='web29apr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('lastname', models.CharField(blank=True, max_length=60)),
                ('number2', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('clg_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
