# Generated by Django 2.2.3 on 2020-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0038_web29apr'),
    ]

    operations = [
        migrations.AddField(
            model_name='web29apr',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='web29apr',
            name='confirmation',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='web29apr',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
